/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certifica_ai;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterContrastIJTheme;
import dao.AlunoDAO;
import dao.CoordenadorDAO;
import dao.CursoDAO;
import factory.ConnectionFactory;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Aluno;
import modelo.Coordenador;
import modelo.Cursos;

/**
 *
 * @author Sandro V Vieira
 */
public class Tela_consultar extends javax.swing.JFrame {

    /**
     * Creates new form Tela_consultar
     */
    public Tela_consultar() {
        initComponents();
        btccalunos.setBackground(new Color(0, 0, 0, 0));
        btnccursos.setBackground(new Color(0, 0, 0, 0));
        btnccoor.setBackground(new Color(0, 0, 0, 0));
        btnvoltar.setBackground(new Color(0, 0, 0, 0));
        btnvoltar1.setBackground(new Color(0, 0, 0, 0));
        btnvoltar2.setBackground(new Color(0, 0, 0, 0));
        btnvoltar3.setBackground(new Color(0, 0, 0, 0));
        btnatualizar.setBackground(new Color(0, 0, 0, 0));
        btndeletar.setBackground(new Color(0, 0, 0, 0));
        btnlimpar.setBackground(new Color(0, 0, 0, 0));
        btnbuscar.setBackground(new Color(0, 0, 0, 0));
        btnatualizar1.setBackground(new Color(0, 0, 0, 0));
        btndeletar1.setBackground(new Color(0, 0, 0, 0));
        btnlimpar1.setBackground(new Color(0, 0, 0, 0));
        btnbuscar1.setBackground(new Color(0, 0, 0, 0));
        btnatualizar2.setBackground(new Color(0, 0, 0, 0));
        btndeletar2.setBackground(new Color(0, 0, 0, 0));
        btnlimpar2.setBackground(new Color(0, 0, 0, 0));
        btnbuscar2.setBackground(new Color(0, 0, 0, 0));
        txtid.setBackground(new Color(0, 0, 0, 0));
        txtid1.setBackground(new Color(0, 0, 0, 0));
        txtid2.setBackground(new Color(0, 0, 0, 0));
        txtnome1.setBackground(new Color(0, 0, 0, 0));
        txtnome2.setBackground(new Color(0, 0, 0, 0));
        txttsemestres.setBackground(new Color(0, 0, 0, 0));
        txtthoras.setBackground(new Color(0, 0, 0, 0));
        txtra.setBackground(new Color(0, 0, 0, 0));
        txtnome.setBackground(new Color(0, 0, 0, 0));
        txtemail.setBackground(new Color(0, 0, 0, 0));
        txtemail1.setBackground(new Color(0, 0, 0, 0));
        txtcurso.setBackground(new Color(0, 0, 0, 0));
        txtcurso1.setBackground(new Color(0, 0, 0, 0));
        txtturno.setBackground(new Color(0, 0, 0, 0));
        txtsemestre.setBackground(new Color(0, 0, 0, 0));
        txtsenha.setBackground(new Color(0, 0, 0, 0));
        txtsenha1.setBackground(new Color(0, 0, 0, 0));
        txtlogin.setBackground(new Color(0, 0, 0, 0));

        txttsemestres.setDocument(new SoNumeros());
        txtthoras.setDocument(new SoNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAINEL_GUIAS = new javax.swing.JTabbedPane();
        CRUD_ALUNOS = new javax.swing.JPanel();
        txtnome = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtcurso = new javax.swing.JTextField();
        txtsemestre = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtra = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        btnatualizar = new javax.swing.JButton();
        btndeletar = new javax.swing.JButton();
        btnvoltar1 = new javax.swing.JButton();
        cad_curso4 = new javax.swing.JLabel();
        CRUD_CURSOS = new javax.swing.JPanel();
        btndeletar1 = new javax.swing.JButton();
        btnvoltar2 = new javax.swing.JButton();
        btnatualizar1 = new javax.swing.JButton();
        btnlimpar1 = new javax.swing.JButton();
        btnbuscar1 = new javax.swing.JButton();
        txtthoras = new javax.swing.JTextField();
        txtid1 = new javax.swing.JTextField();
        txttsemestres = new javax.swing.JTextField();
        txtnome1 = new javax.swing.JTextField();
        cad_curso3 = new javax.swing.JLabel();
        CRUD_COOR = new javax.swing.JPanel();
        btnvoltar3 = new javax.swing.JButton();
        btndeletar2 = new javax.swing.JButton();
        btnatualizar2 = new javax.swing.JButton();
        btnlimpar2 = new javax.swing.JButton();
        btnbuscar2 = new javax.swing.JButton();
        txtsenha1 = new javax.swing.JTextField();
        txtturno = new javax.swing.JTextField();
        txtid2 = new javax.swing.JTextField();
        txtcurso1 = new javax.swing.JTextField();
        txtemail1 = new javax.swing.JTextField();
        txtnome2 = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        lblfundo3 = new javax.swing.JLabel();
        btccalunos = new javax.swing.JButton();
        btnccursos = new javax.swing.JButton();
        btnccoor = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        lblmenufundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CRUD_ALUNOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtnome.setBorder(null);
        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        CRUD_ALUNOS.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 401, 330, 20));

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtemail.setBorder(null);
        CRUD_ALUNOS.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 330, 20));

        txtcurso.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcurso.setBorder(null);
        CRUD_ALUNOS.add(txtcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 130, 20));

        txtsemestre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsemestre.setBorder(null);
        CRUD_ALUNOS.add(txtsemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 80, 20));

        txtsenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsenha.setBorder(null);
        CRUD_ALUNOS.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 330, 20));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtid.setBorder(null);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        CRUD_ALUNOS.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 140, 30));

        txtra.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtra.setBorder(null);
        txtra.setEnabled(false);
        CRUD_ALUNOS.add(txtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 322, 330, 20));

        btnbuscar.setBorder(null);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        CRUD_ALUNOS.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 170, 30));

        btnlimpar.setBorder(null);
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });
        CRUD_ALUNOS.add(btnlimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 180, 30));

        btnatualizar.setBorder(null);
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });
        CRUD_ALUNOS.add(btnatualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 280, 30));

        btndeletar.setBorder(null);
        btndeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarActionPerformed(evt);
            }
        });
        CRUD_ALUNOS.add(btndeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 280, 30));

        btnvoltar1.setBorder(null);
        btnvoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar1ActionPerformed(evt);
            }
        });
        CRUD_ALUNOS.add(btnvoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 100, 30));

        cad_curso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunos_crud3.png"))); // NOI18N
        CRUD_ALUNOS.add(cad_curso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 740));

        PAINEL_GUIAS.addTab("tab2", CRUD_ALUNOS);

        CRUD_CURSOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndeletar1.setBorder(null);
        btndeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletar1ActionPerformed(evt);
            }
        });
        CRUD_CURSOS.add(btndeletar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, 280, 30));

        btnvoltar2.setBorder(null);
        btnvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar2ActionPerformed(evt);
            }
        });
        CRUD_CURSOS.add(btnvoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 100, 30));

        btnatualizar1.setBorder(null);
        btnatualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizar1ActionPerformed(evt);
            }
        });
        CRUD_CURSOS.add(btnatualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 280, 30));

        btnlimpar1.setBorder(null);
        btnlimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpar1ActionPerformed(evt);
            }
        });
        CRUD_CURSOS.add(btnlimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 180, 30));

        btnbuscar1.setBorder(null);
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });
        CRUD_CURSOS.add(btnbuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 180, 30));

        txtthoras.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtthoras.setBorder(null);
        CRUD_CURSOS.add(txtthoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 531, 560, 20));

        txtid1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtid1.setBorder(null);
        txtid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid1ActionPerformed(evt);
            }
        });
        CRUD_CURSOS.add(txtid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 130, 30));

        txttsemestres.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txttsemestres.setBorder(null);
        CRUD_CURSOS.add(txttsemestres, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 459, 560, 30));

        txtnome1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtnome1.setBorder(null);
        txtnome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnome1ActionPerformed(evt);
            }
        });
        CRUD_CURSOS.add(txtnome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 391, 560, 30));

        cad_curso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cursos_crud.png"))); // NOI18N
        CRUD_CURSOS.add(cad_curso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 740));

        PAINEL_GUIAS.addTab("tab1", CRUD_CURSOS);

        CRUD_COOR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvoltar3.setBorder(null);
        btnvoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar3ActionPerformed(evt);
            }
        });
        CRUD_COOR.add(btnvoltar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 100, 30));

        btndeletar2.setBorder(null);
        btndeletar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletar2ActionPerformed(evt);
            }
        });
        CRUD_COOR.add(btndeletar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 290, 30));

        btnatualizar2.setBorder(null);
        btnatualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizar2ActionPerformed(evt);
            }
        });
        CRUD_COOR.add(btnatualizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 290, 30));

        btnlimpar2.setBorder(null);
        btnlimpar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpar2ActionPerformed(evt);
            }
        });
        CRUD_COOR.add(btnlimpar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 180, 40));

        btnbuscar2.setBorder(null);
        btnbuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar2ActionPerformed(evt);
            }
        });
        CRUD_COOR.add(btnbuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 180, 40));

        txtsenha1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsenha1.setBorder(null);
        CRUD_COOR.add(txtsenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 558, 90, 20));

        txtturno.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtturno.setBorder(null);
        CRUD_COOR.add(txtturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 90, 30));

        txtid2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtid2.setBorder(null);
        txtid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid2ActionPerformed(evt);
            }
        });
        CRUD_COOR.add(txtid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 130, 20));

        txtcurso1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcurso1.setBorder(null);
        CRUD_COOR.add(txtcurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 120, 30));

        txtemail1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtemail1.setBorder(null);
        CRUD_COOR.add(txtemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 439, 320, 30));

        txtnome2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtnome2.setBorder(null);
        txtnome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnome2ActionPerformed(evt);
            }
        });
        CRUD_COOR.add(txtnome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 320, 30));

        txtlogin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtlogin.setBorder(null);
        CRUD_COOR.add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 558, 120, 20));

        lblfundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coordenadores_crud.png"))); // NOI18N
        lblfundo3.setPreferredSize(new java.awt.Dimension(1123, 758));
        CRUD_COOR.add(lblfundo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        PAINEL_GUIAS.addTab("tab2", CRUD_COOR);

        getContentPane().add(PAINEL_GUIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -33, 1120, -1));

        btccalunos.setBorder(null);
        btccalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btccalunosActionPerformed(evt);
            }
        });
        getContentPane().add(btccalunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 200, 40));

        btnccursos.setBorder(null);
        btnccursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnccursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 200, 40));

        btnccoor.setBorder(null);
        btnccoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccoorActionPerformed(evt);
            }
        });
        getContentPane().add(btnccoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 200, 40));

        btnvoltar.setBorder(null);
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 200, 40));

        lblmenufundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu_consul.png"))); // NOI18N
        getContentPane().add(lblmenufundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 290, 730));

        setSize(new java.awt.Dimension(1377, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btccalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btccalunosActionPerformed
        PAINEL_GUIAS.setSelectedIndex(0);
    }//GEN-LAST:event_btccalunosActionPerformed

    private void btnccursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccursosActionPerformed
        PAINEL_GUIAS.setSelectedIndex(1);
    }//GEN-LAST:event_btnccursosActionPerformed

    private void btnccoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccoorActionPerformed
        PAINEL_GUIAS.setSelectedIndex(2);
    }//GEN-LAST:event_btnccoorActionPerformed

    public void ativaBotao1() {
        btnatualizar.setEnabled(true);
        btndeletar.setEnabled(true);
    }

    public void ativaBotao2() {
        btnatualizar1.setEnabled(true);
        btndeletar1.setEnabled(true);

    }

    public void ativaBotao3() {
        btnatualizar2.setEnabled(true);
        btndeletar2.setEnabled(true);

    }

    public void desativaBotao1() {
        btnatualizar.setEnabled(false);
        btndeletar.setEnabled(false);

    }

    public void desativaBotao2() {
        btnatualizar1.setEnabled(false);
        btndeletar1.setEnabled(false);
    }

    public void desativaBotao3() {
        btnatualizar2.setEnabled(false);
        btndeletar2.setEnabled(false);
    }

    public void limpacampos1() {
        txtra.setText("");
        txtnome.setText("");
        txtemail.setText("");
        txtcurso.setText("");
        txtsemestre.setText("");
        txtsenha.setText("");
    }

    public void limpacampos2() {
        txtnome1.setText("");
        txttsemestres.setText("");
        txtthoras.setText("");
    }

    public void limpacampos3() {
        txtnome2.setText("");
        txtemail1.setText("");
        txtcurso1.setText("");
        txtturno.setText("");
        txtlogin.setText("");
        txtsenha1.setText("");
    }

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        Tela_secretaria sec = new Tela_secretaria();
        sec.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        ativaBotao1();
        try {
            Aluno aluno = new Aluno();
            aluno.setId(txtid.getText());
            AlunoDAO dao = new AlunoDAO();
            dao.select(aluno);
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select * from tab_alunos where id = ? ";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, txtid.getText());
            ResultSet rs = stmt.executeQuery();

            if (txtid.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Id!");
            } else if (rs.next()) {
                txtra.setText(aluno.getRa());
                txtnome.setText(aluno.getNome());
                txtemail.setText(aluno.getEmail());
                txtcurso.setText(aluno.getCurso_aluno());
                txtsemestre.setText(aluno.getSemestre());
                txtsenha.setText(aluno.getSenha());
                ;
            } else {
                JOptionPane.showMessageDialog(null, "Usuario não encontrado");
                limpacampos1();
             //   desativaBotao1();

            }
            rs.close();
            connection.close();
        } catch (Exception e) {

        }    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        txtra.setText("");
        txtnome.setText("");
        txtemail.setText("");
        txtsenha.setText("");
        txtcurso.setText("");
        txtsemestre.setText("");
        //desativaBotao1();
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
        if (txtid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Id");
        } else {

            Aluno aluno = new Aluno();
            aluno.setNome(txtnome.getText());
            aluno.setEmail(txtemail.getText());
            aluno.setCurso_aluno(txtcurso.getText());
            aluno.setSemestre(txtsemestre.getText());
            aluno.setSenha(txtsenha.getText());
            aluno.setId(txtid.getText());

            AlunoDAO dao = new AlunoDAO();
            dao.update(aluno);
            limpacampos1();
           // desativaBotao1();

        }    }//GEN-LAST:event_btnatualizarActionPerformed

    private void btndeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarActionPerformed
        if (txtid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Id!");

        } else {
            Aluno aluno = new Aluno();
            aluno.setId(txtid.getText());
            AlunoDAO dao = new AlunoDAO();
            dao.delete(aluno);
            limpacampos1();

          //  desativaBotao1();
        }    }//GEN-LAST:event_btndeletarActionPerformed

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void btnvoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar1ActionPerformed
        PAINEL_GUIAS.setSelectedIndex(0);    }//GEN-LAST:event_btnvoltar1ActionPerformed

    private void btndeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletar1ActionPerformed
        if (txtid1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Id!");

        } else {
            Cursos cursos = new Cursos();
            cursos.setId(txtid1.getText());
            CursoDAO dao = new CursoDAO();
            dao.delete(cursos);

            limpacampos2();
           // desativaBotao2();
        }

    }//GEN-LAST:event_btndeletar1ActionPerformed

    private void btnvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar2ActionPerformed
        PAINEL_GUIAS.setSelectedIndex(0);     }//GEN-LAST:event_btnvoltar2ActionPerformed

    private void btnatualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizar1ActionPerformed
        if (txtid1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Id");
        } else {

            Cursos cursos = new Cursos();
            cursos.setNome(txtnome1.getText());
            cursos.setTotal_semestres(txttsemestres.getText());
            cursos.setTotal_horas(txtthoras.getText());
            cursos.setId(txtid1.getText());

            CursoDAO dao = new CursoDAO();
            dao.update(cursos);
            limpacampos2();
           // desativaBotao2();

        }    }//GEN-LAST:event_btnatualizar1ActionPerformed

    private void btnlimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpar1ActionPerformed
        limpacampos2();
        //desativaBotao2();
    }//GEN-LAST:event_btnlimpar1ActionPerformed

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        ativaBotao2();
        try {
            Cursos cursos = new Cursos();
            cursos.setId(txtid1.getText());
            CursoDAO dao = new CursoDAO();
            dao.select(cursos);
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select * from tab_cursos where id = ? ";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, txtid1.getText());
            ResultSet rs = stmt.executeQuery();

            if (txtid1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Id!");
            } else if (rs.next()) {
                txtnome1.setText(cursos.getNome());
                txttsemestres.setText(cursos.getTotal_semestres());
                txtthoras.setText(cursos.getTotal_horas());
                ;
            } else {
                JOptionPane.showMessageDialog(null, "Curso não encontrado");
               // desativaBotao2();
                limpacampos2();

            }
            rs.close();
            connection.close();
        } catch (Exception e) {

        }    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void txtid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid1ActionPerformed

    private void txtnome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnome1ActionPerformed

    private void btnvoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar3ActionPerformed
        PAINEL_GUIAS.setSelectedIndex(1);    }//GEN-LAST:event_btnvoltar3ActionPerformed

    private void btndeletar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletar2ActionPerformed
        if (txtid2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Id!");

        } else {
            Coordenador coor = new Coordenador();
            coor.setId(txtid2.getText());
            CoordenadorDAO dao = new CoordenadorDAO();
            dao.delete(coor);
            limpacampos3();

            //desativaBotao3();
        }     }//GEN-LAST:event_btndeletar2ActionPerformed

    private void btnatualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizar2ActionPerformed
        if (txtid2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o Id");
        } else {

            Coordenador coor = new Coordenador();
            coor.setNome(txtnome2.getText());
            coor.setEmail(txtemail1.getText());
            coor.setCurso_coor(txtcurso1.getText());
            coor.setTurno(txtturno.getText());
            coor.setLogin(txtlogin.getText());
            coor.setSenha(txtsenha1.getText());
            coor.setId(txtid2.getText());

            CoordenadorDAO dao = new CoordenadorDAO();
            dao.update(coor);
            limpacampos3();
            //desativaBotao3();

        }    }//GEN-LAST:event_btnatualizar2ActionPerformed

    private void btnlimpar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpar2ActionPerformed
       // limpacampos3();
        //desativaBotao3();
    }//GEN-LAST:event_btnlimpar2ActionPerformed

    private void btnbuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar2ActionPerformed
        ativaBotao3();
        try {
            Coordenador coor = new Coordenador();
            coor.setId(txtid2.getText());
            CoordenadorDAO dao = new CoordenadorDAO();
            dao.select(coor);
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select * from tab_coordenador where id = ? ";
            PreparedStatement stmt = connection.prepareStatement(sql);
            stmt.setString(1, txtid2.getText());
            ResultSet rs = stmt.executeQuery();

            if (txtid2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Informe o Id!");
            } else if (rs.next()) {
                txtnome2.setText(coor.getNome());
                txtemail1.setText(coor.getEmail());
                txtcurso1.setText(coor.getCurso_coor());
                txtturno.setText(coor.getTurno());
                txtlogin.setText(coor.getLogin());
                txtsenha1.setText(coor.getSenha());
                ;
            } else {
                JOptionPane.showMessageDialog(null, "Coordenador não encontrado");
                //desativaBotao3();
                limpacampos3();

            }
            rs.close();
            connection.close();
        } catch (Exception e) {
        }
     }//GEN-LAST:event_btnbuscar2ActionPerformed

    private void txtid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid2ActionPerformed

    private void txtnome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnome2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            // FlatMaterialLighterContrastIJTheme.setup();
            // UIManager.put("TextComponent.arc", 10);
            // UIManager.put("Button.arc", 100);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CRUD_ALUNOS;
    private javax.swing.JPanel CRUD_COOR;
    private javax.swing.JPanel CRUD_CURSOS;
    private javax.swing.JTabbedPane PAINEL_GUIAS;
    private javax.swing.JButton btccalunos;
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btnatualizar1;
    private javax.swing.JButton btnatualizar2;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JButton btnbuscar2;
    private javax.swing.JButton btnccoor;
    private javax.swing.JButton btnccursos;
    private javax.swing.JButton btndeletar;
    private javax.swing.JButton btndeletar1;
    private javax.swing.JButton btndeletar2;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JButton btnlimpar1;
    private javax.swing.JButton btnlimpar2;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JButton btnvoltar1;
    private javax.swing.JButton btnvoltar2;
    private javax.swing.JButton btnvoltar3;
    private javax.swing.JLabel cad_curso3;
    private javax.swing.JLabel cad_curso4;
    private javax.swing.JLabel lblfundo3;
    private javax.swing.JLabel lblmenufundo;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtcurso1;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemail1;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtid1;
    private javax.swing.JTextField txtid2;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnome1;
    private javax.swing.JTextField txtnome2;
    private javax.swing.JTextField txtra;
    private javax.swing.JTextField txtsemestre;
    private javax.swing.JTextField txtsenha;
    private javax.swing.JTextField txtsenha1;
    private javax.swing.JTextField txtthoras;
    private javax.swing.JTextField txttsemestres;
    private javax.swing.JTextField txtturno;
    // End of variables declaration//GEN-END:variables
}
