/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certifica_ai;

import com.formdev.flatlaf.intellijthemes.FlatGradiantoDarkFuchsiaIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterContrastIJTheme;
import factory.ConnectionFactory;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Sandro V Vieira
 */
public class Tela_login extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public Tela_login() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);       
        btnsair.setBackground(new Color(0, 0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtra = new javax.swing.JTextField();
        btnentrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbtipo = new javax.swing.JComboBox<>();
        txtsenha = new javax.swing.JPasswordField();
        lbl2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        btnsair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 360, 250, 40));

        btnentrar.setText("ENTRAR");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 500, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 180, 150, -1));

        cbtipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aluno", "Coordenador", "Secretaria" }));
        cbtipo.setToolTipText("");
        cbtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipoActionPerformed(evt);
            }
        });
        getContentPane().add(cbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 250, 40));

        txtsenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 250, 40));

        lbl2.setText("Senha");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, -1, -1));

        jLabel4.setText("Tipo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 270, -1, -1));

        lbl1.setText("RA");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, -1, -1));

        btnsair.setBorder(null);
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1205, 90, 60, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/login3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 730));

        setSize(new java.awt.Dimension(1377, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        if (cbtipo.getSelectedIndex() == 0) {
            try {
                Connection connection = new ConnectionFactory().getConnection();    //puxar conexão co m banco de dados
                String sql = "select * from tab_alunos where ra = ? and senha = ?";    //comandos no mysql
                PreparedStatement stmt = connection.prepareCall(sql);   //preparação dos dados para enviar para a conexao, devido a variavel sql
                stmt.setString(1, txtra.getText());   //quais as informações vou mandar? 1 = campo1(usuario)
                stmt.setString(2, new String(txtsenha.getPassword()));    //quais as informações vou mandar? 2 = campo2(senha)
                ResultSet rs = stmt.executeQuery();    //existe a informação no banco ou não?
                // executeQuery = executa a conulta no banco
                //stmt prepara a informação
                if (rs.next()) {  //se tiver a informação no banco
                    Tela_aluno aluno = new Tela_aluno(rs.getInt("id"));
                    aluno.setVisible(true);
                    dispose();
                } else if ((txtra.getText().isEmpty()) || (txtsenha.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
                } else {

                    JOptionPane.showMessageDialog(null, "RA ou senha inválidos!\nEfetue o cadastro ou verifique novamente suas informações!");
                }
                txtsenha.setText("");
                stmt.close();
                connection.close();
            } catch (Exception e) {
            }

        }
        if (cbtipo.getSelectedIndex() == 1) {
            try {
                Connection connection = new ConnectionFactory().getConnection();    //puxar conexão co m banco de dados
                String sql = "select * from tab_coordenador where login = ? and senha = ?";    //comandos no mysql
                PreparedStatement stmt = connection.prepareCall(sql);   //preparação dos dados para enviar para a conexao, devido a variavel sql
                stmt.setString(1, txtra.getText());   //quais as informações vou mandar? 1 = campo1(usuario)
                stmt.setString(2, new String(txtsenha.getPassword()));    //quais as informações vou mandar? 2 = campo2(senha)
                ResultSet rs = stmt.executeQuery();    //existe a informação no banco ou não?
                // executeQuery = executa a conulta no banco
                //stmt prepara a informação
                if (rs.next()) {  //se tiver a informação no banco
                    Tela_coordenador coor = new Tela_coordenador();
                    coor.setVisible(true);
                    dispose();
                } else if ((txtra.getText().isEmpty()) || (txtsenha.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
                } else {

                    JOptionPane.showMessageDialog(null, "RA ou senha inválidos!\nEfetue o cadastro ou verifique novamente suas informações!");
                }
                txtsenha.setText("");
                stmt.close();
                connection.close();
            } catch (Exception e) {
            }

        }
        if (cbtipo.getSelectedIndex() == 2) {
            try {
                Connection connection = new ConnectionFactory().getConnection();    //puxar conexão co m banco de dados
                String sql = "select * from tab_secretaria where login = ? and senha = ?";    //comandos no mysql
                PreparedStatement stmt = connection.prepareCall(sql);   //preparação dos dados para enviar para a conexao, devido a variavel sql
                stmt.setString(1, txtra.getText());   //quais as informações vou mandar? 1 = campo1(usuario)
                stmt.setString(2, new String(txtsenha.getPassword()));    //quais as informações vou mandar? 2 = campo2(senha)
                ResultSet rs = stmt.executeQuery();    //existe a informação no banco ou não?
                // executeQuery = executa a conulta no banco
                //stmt prepara a informação
                if (rs.next()) {  //se tiver a informação no banco
                    Tela_secretaria sec = new Tela_secretaria();
                    sec.setVisible(true);
                    dispose();
                } else if ((txtra.getText().isEmpty()) || (txtsenha.getText().isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
                } else {

                    JOptionPane.showMessageDialog(null, "RA ou senha inválidos!\nEfetue o cadastro ou verifique novamente suas informações!");
                }
                txtsenha.setText("");
                stmt.close();
                connection.close();
            } catch (Exception e) {
            }

        }

    }//GEN-LAST:event_btnentrarActionPerformed

    private void cbtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipoActionPerformed
        if (cbtipo.getSelectedIndex() == 0) {
            lbl1.setText("RA");
            lbl2.setText("senha");
        }
        if (cbtipo.getSelectedIndex() == 1) {
            lbl1.setText("Login");
            lbl2.setText("senha");
        }
        if (cbtipo.getSelectedIndex() == 2) {
            lbl1.setText("Login");
            lbl2.setText("senha");
        }
    }//GEN-LAST:event_cbtipoActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        int a = JOptionPane.showConfirmDialog(null, " Confirmar saida?", "Sair", JOptionPane.OK_CANCEL_OPTION);
        if (a == JOptionPane.OK_OPTION) {
            dispose();
        }

    }//GEN-LAST:event_btnsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            FlatMaterialLighterContrastIJTheme.setup();
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("Button.arc", 100);

        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JButton btnsair;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JTextField txtra;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
