/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certifica_ai;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterContrastIJTheme;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Aluno;
import dao.AlunoDAO;
import dao.CoordenadorDAO;
import dao.CursoDAO;
import modelo.Coordenador;
import modelo.Cursos;

/**
 *
 * @author Sandro V Vieira
 */
public class Tela_secretaria extends javax.swing.JFrame {

    /**
     * Creates new form Tela_secretaria
     */
    public Tela_secretaria() {
        initComponents();
        btncalunos.setBackground(new Color(0, 0, 0, 0));
        btnccursos.setBackground(new Color(0, 0, 0, 0));
        btnccoor.setBackground(new Color(0, 0, 0, 0));
        btnconsul.setBackground(new Color(0, 0, 0, 0));
        btntab.setBackground(new Color(0, 0, 0, 0));
        btnsair.setBackground(new Color(0, 0, 0, 0));
        btnvoltar.setBackground(new Color(0, 0, 0, 0));
        btnvoltar1.setBackground(new Color(0, 0, 0, 0));
        btnvoltar2.setBackground(new Color(0, 0, 0, 0));
        btnsalvar.setBackground(new Color(0, 0, 0, 0));
        btnsalvar2.setBackground(new Color(0, 0, 0, 0));
        btnsalvar3.setBackground(new Color(0, 0, 0, 0));
        txtra.setBackground(new Color(0, 0, 0, 0));
        txtnome.setBackground(new Color(0, 0, 0, 0));
        txtnome2.setBackground(new Color(0, 0, 0, 0));
        txtnome3.setBackground(new Color(0, 0, 0, 0));
        txtemail.setBackground(new Color(0, 0, 0, 0));
        txtemail2.setBackground(new Color(0, 0, 0, 0));
        txtcurso.setBackground(new Color(0, 0, 0, 0));
        txtcurso2.setBackground(new Color(0, 0, 0, 0));
        txtsemestre.setBackground(new Color(0, 0, 0, 0));
        txttsemestres.setBackground(new Color(0, 0, 0, 0));
        txthoras.setBackground(new Color(0, 0, 0, 0));
        txtturno.setBackground(new Color(0, 0, 0, 0));
        txtsenha.setBackground(new Color(0, 0, 0, 0));
        txtlogin.setBackground(new Color(0, 0, 0, 0));
        txtsenha1.setBackground(new Color(0, 0, 0, 0));

        txttsemestres.setDocument(new SoNumeros());
        txthoras.setDocument(new SoNumeros());
        txtra.setDocument(new SoNumeros());
        txtsemestre.setDocument(new SoNumeros());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAINEL_GUIAS = new javax.swing.JTabbedPane();
        CADASTRO_ALUNO = new javax.swing.JPanel();
        btnvoltar = new javax.swing.JButton();
        txtra = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtsemestre = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtsenha = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JButton();
        txtcurso = new javax.swing.JComboBox<>();
        lblfundo1 = new javax.swing.JLabel();
        CADASTRO_CURSO = new javax.swing.JPanel();
        btnvoltar1 = new javax.swing.JButton();
        txthoras = new javax.swing.JTextField();
        txtnome2 = new javax.swing.JTextField();
        txttsemestres = new javax.swing.JTextField();
        btnsalvar2 = new javax.swing.JButton();
        lblfundo2 = new javax.swing.JLabel();
        CADASTRO_COOR = new javax.swing.JPanel();
        btnvoltar2 = new javax.swing.JButton();
        txtnome3 = new javax.swing.JTextField();
        txtturno = new javax.swing.JTextField();
        txtemail2 = new javax.swing.JTextField();
        btnsalvar3 = new javax.swing.JButton();
        txtlogin = new javax.swing.JTextField();
        txtsenha1 = new javax.swing.JTextField();
        txtcurso2 = new javax.swing.JComboBox<>();
        lblfundo3 = new javax.swing.JLabel();
        btnccursos = new javax.swing.JButton();
        btnccoor = new javax.swing.JButton();
        btnconsul = new javax.swing.JButton();
        btntab = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        btncalunos = new javax.swing.JButton();
        lblfundomenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CADASTRO_ALUNO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvoltar.setBorder(null);
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        CADASTRO_ALUNO.add(btnvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 90, 40));

        txtra.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtra.setBorder(null);
        txtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtraActionPerformed(evt);
            }
        });
        CADASTRO_ALUNO.add(txtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 190, 40));

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtemail.setBorder(null);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        CADASTRO_ALUNO.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 560, 20));

        txtsemestre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsemestre.setBorder(null);
        CADASTRO_ALUNO.add(txtsemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 130, 20));

        txtnome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtnome.setBorder(null);
        CADASTRO_ALUNO.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 560, 30));

        txtsenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtsenha.setBorder(null);
        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        CADASTRO_ALUNO.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 560, 20));

        btnsalvar.setBorder(null);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        CADASTRO_ALUNO.add(btnsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 670, 90, 40));

        txtcurso.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engenharia da Computação", "Análise e Desenvolvimento de Sistemas", "Gestão de T.I", "Banco de Dados", "Jogos Digitais", "Engenharia Química", "Engenharia de Produção", "Engenharia Civil", "Engenharia Elétrica", "Engenharia Mecânica", "Engenharia Mecatrônica", "Engenharia de Alimentos", "Engenharia Agronômica", "Arquitetura e Urbanismo", "Enfermagem", "Odontologia", "Psicologia", "Biomedicina" }));
        txtcurso.setBorder(null);
        txtcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcursoActionPerformed(evt);
            }
        });
        CADASTRO_ALUNO.add(txtcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 380, 20));

        lblfundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro_alunos.png"))); // NOI18N
        lblfundo1.setPreferredSize(new java.awt.Dimension(1123, 758));
        CADASTRO_ALUNO.add(lblfundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        PAINEL_GUIAS.addTab("tab2", CADASTRO_ALUNO);

        CADASTRO_CURSO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvoltar1.setBorder(null);
        btnvoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar1ActionPerformed(evt);
            }
        });
        CADASTRO_CURSO.add(btnvoltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 90, 40));

        txthoras.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txthoras.setBorder(null);
        txthoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthorasActionPerformed(evt);
            }
        });
        CADASTRO_CURSO.add(txthoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 531, 560, 20));

        txtnome2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtnome2.setBorder(null);
        CADASTRO_CURSO.add(txtnome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 560, 40));

        txttsemestres.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txttsemestres.setBorder(null);
        CADASTRO_CURSO.add(txttsemestres, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 458, 560, 30));

        btnsalvar2.setBorder(null);
        btnsalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar2ActionPerformed(evt);
            }
        });
        CADASTRO_CURSO.add(btnsalvar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, 90, 50));

        lblfundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro_cursos.png"))); // NOI18N
        CADASTRO_CURSO.add(lblfundo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 740));

        PAINEL_GUIAS.addTab("tab1", CADASTRO_CURSO);

        CADASTRO_COOR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnvoltar2.setBorder(null);
        btnvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar2ActionPerformed(evt);
            }
        });
        CADASTRO_COOR.add(btnvoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 90, 40));

        txtnome3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnome3.setBorder(null);
        CADASTRO_COOR.add(txtnome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 341, 560, 30));

        txtturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtturno.setBorder(null);
        CADASTRO_COOR.add(txtturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 477, 140, 20));

        txtemail2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtemail2.setBorder(null);
        CADASTRO_COOR.add(txtemail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 404, 560, 40));

        btnsalvar3.setBorder(null);
        btnsalvar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar3ActionPerformed(evt);
            }
        });
        CADASTRO_COOR.add(btnsalvar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, 90, 40));

        txtlogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtlogin.setBorder(null);
        CADASTRO_COOR.add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 560, 20));

        txtsenha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsenha1.setBorder(null);
        CADASTRO_COOR.add(txtsenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 560, 20));

        txtcurso2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtcurso2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engenharia da Computação", "Análise e Desenvolvimento de Sistemas", "Gestão de T.I", "Banco de Dados", "Jogos Digitais", "Engenharia Química", "Engenharia de Produção", "Engenharia Civil", "Engenharia Elétrica", "Engenharia Mecânica", "Engenharia Mecatrônica", "Engenharia de Alimentos", "Engenharia Agronômica", "Arquitetura e Urbanismo", "Enfermagem", "Odontologia", "Psicologia", "Biomedicina" }));
        txtcurso2.setBorder(null);
        txtcurso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcurso2ActionPerformed(evt);
            }
        });
        CADASTRO_COOR.add(txtcurso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 476, 380, 20));

        lblfundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastro_coordenadores.png"))); // NOI18N
        lblfundo3.setPreferredSize(new java.awt.Dimension(1123, 758));
        CADASTRO_COOR.add(lblfundo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        PAINEL_GUIAS.addTab("tab2", CADASTRO_COOR);

        getContentPane().add(PAINEL_GUIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -33, 1120, -1));

        btnccursos.setBorder(null);
        btnccursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnccursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 200, 40));

        btnccoor.setBorder(null);
        btnccoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnccoorActionPerformed(evt);
            }
        });
        getContentPane().add(btnccoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 200, 40));

        btnconsul.setBorder(null);
        btnconsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsulActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 200, 40));

        btntab.setBorder(null);
        btntab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntabActionPerformed(evt);
            }
        });
        getContentPane().add(btntab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 200, 40));

        btnsair.setBorder(null);
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 200, 40));

        btncalunos.setBorder(null);
        btncalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalunosActionPerformed(evt);
            }
        });
        getContentPane().add(btncalunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 200, 40));

        lblfundomenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu_secretaria.png"))); // NOI18N
        getContentPane().add(lblfundomenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 290, 730));

        setSize(new java.awt.Dimension(1377, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalunosActionPerformed
        PAINEL_GUIAS.setSelectedIndex(0);
    }//GEN-LAST:event_btncalunosActionPerformed

    private void btnccursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccursosActionPerformed
        PAINEL_GUIAS.setSelectedIndex(1);
    }//GEN-LAST:event_btnccursosActionPerformed

    private void btnccoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnccoorActionPerformed
        PAINEL_GUIAS.setSelectedIndex(2);
    }//GEN-LAST:event_btnccoorActionPerformed

    private void btnconsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsulActionPerformed
        Tela_consultar consul = new Tela_consultar();
        consul.setVisible(true);
        dispose();    }//GEN-LAST:event_btnconsulActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        Tela_login login = new Tela_login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    private void btntabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntabActionPerformed
        Tela_tabelas tabs = new Tela_tabelas();
        tabs.setVisible(true);
        dispose();
    }//GEN-LAST:event_btntabActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        PAINEL_GUIAS.setSelectedIndex(0);    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnvoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar1ActionPerformed
        PAINEL_GUIAS.setSelectedIndex(0);     }//GEN-LAST:event_btnvoltar1ActionPerformed

    private void btnvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar2ActionPerformed
        PAINEL_GUIAS.setSelectedIndex(1);     }//GEN-LAST:event_btnvoltar2ActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        Aluno alunos = new Aluno();
        alunos.setRa(txtra.getText());
        alunos.setNome(txtnome.getText());
        alunos.setEmail(txtemail.getText());
        alunos.setCurso_aluno((String) txtcurso.getSelectedItem());
        alunos.setSemestre(txtsemestre.getText());
        alunos.setSenha(txtsenha.getText());

        // fazendo a validação dos dados
        if ((txtra.getText().isEmpty()) || (txtnome.getText().isEmpty()) || (txtemail.getText().isEmpty()) || (txtsemestre.getText().isEmpty()) || (txtsenha.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            AlunoDAO dao = new AlunoDAO();
            dao.adiciona(alunos);
            JOptionPane.showMessageDialog(null, "Aluno '" + txtnome.getText() + "' cadastrado com sucesso!");
            txtra.setText("");
            txtnome.setText("");
            txtemail.setText("");
            txtsemestre.setText("");
            txtsenha.setText("");
        }    }//GEN-LAST:event_btnsalvarActionPerformed

    private void txthorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorasActionPerformed

    private void btnsalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar2ActionPerformed
        Cursos cursos = new Cursos();
        cursos.setNome(txtnome2.getText());
        cursos.setTotal_semestres(txttsemestres.getText());
        cursos.setTotal_horas(txthoras.getText());

        // fazendo a validação dos dados
        if ((txtnome2.getText().isEmpty()) || (txttsemestres.getText().isEmpty()) || (txthoras.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            CursoDAO dao = new CursoDAO();
            dao.adiciona(cursos);
            JOptionPane.showMessageDialog(null, "Curso '" + txtnome2.getText() + "' cadastrado com sucesso!");
            txttsemestres.setText("");
            txtnome2.setText("");
            txthoras.setText("");

        }    }//GEN-LAST:event_btnsalvar2ActionPerformed

    private void btnsalvar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar3ActionPerformed
        Coordenador coor = new Coordenador();
        coor.setNome(txtnome3.getText());
        coor.setEmail(txtemail2.getText());
        coor.setCurso_coor((String) txtcurso2.getSelectedItem());
        coor.setTurno(txtturno.getText());
        coor.setLogin(txtlogin.getText());
        coor.setSenha(txtsenha1.getText());

        // fazendo a validação dos dados
        if ((txtnome3.getText().isEmpty()) || (txtemail2.getText().isEmpty()) || (txtturno.getText().isEmpty()) || (txtlogin.getText().isEmpty()) || (txtsenha1.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retornar vazios");
        } else {
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
            CoordenadorDAO dao = new CoordenadorDAO();
            dao.adiciona(coor);
            JOptionPane.showMessageDialog(null, "Coordenador '" + txtnome3.getText() + "' cadastrado com sucesso!");
            txtnome3.setText("");
            txtemail2.setText("");
            txtturno.setText("");
            txtlogin.setText("");
            txtsenha1.setText("");
        }    }//GEN-LAST:event_btnsalvar3ActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void txtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtraActionPerformed

    private void txtcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcursoActionPerformed

    private void txtcurso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcurso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcurso2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            FlatMaterialLighterContrastIJTheme.setup();
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("Button.arc", 100);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_secretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_secretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CADASTRO_ALUNO;
    private javax.swing.JPanel CADASTRO_COOR;
    private javax.swing.JPanel CADASTRO_CURSO;
    private javax.swing.JTabbedPane PAINEL_GUIAS;
    private javax.swing.JButton btncalunos;
    private javax.swing.JButton btnccoor;
    private javax.swing.JButton btnccursos;
    private javax.swing.JButton btnconsul;
    private javax.swing.JButton btnsair;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JButton btnsalvar2;
    private javax.swing.JButton btnsalvar3;
    private javax.swing.JButton btntab;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JButton btnvoltar1;
    private javax.swing.JButton btnvoltar2;
    private javax.swing.JLabel lblfundo1;
    private javax.swing.JLabel lblfundo2;
    private javax.swing.JLabel lblfundo3;
    private javax.swing.JLabel lblfundomenu;
    private javax.swing.JComboBox<String> txtcurso;
    private javax.swing.JComboBox<String> txtcurso2;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtemail2;
    private javax.swing.JTextField txthoras;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnome2;
    private javax.swing.JTextField txtnome3;
    private javax.swing.JTextField txtra;
    private javax.swing.JTextField txtsemestre;
    private javax.swing.JTextField txtsenha;
    private javax.swing.JTextField txtsenha1;
    private javax.swing.JTextField txttsemestres;
    private javax.swing.JTextField txtturno;
    // End of variables declaration//GEN-END:variables
}
