/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package certifica_ai;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterContrastIJTheme;
import factory.ConnectionFactory;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandro V Vieira
 */
public class Tela_tabelas extends javax.swing.JFrame {

    /**
     * Creates new form Tela_tabelas
     */
    public Tela_tabelas() {
        initComponents();
        btntalunos.setBackground(new Color(0, 0, 0, 0));
        btntcursos.setBackground(new Color(0, 0, 0, 0));
        btntcoor.setBackground(new Color(0, 0, 0, 0));
        btnvoltar.setBackground(new Color(0, 0, 0, 0));
        btnvoltar2.setBackground(new Color(0, 0, 0, 0));
        btnvoltar3.setBackground(new Color(0, 0, 0, 0));
        btnvoltar4.setBackground(new Color(0, 0, 0, 0));
        btnimprimir.setBackground(new Color(0, 0, 0, 0));
        btnimprimir1.setBackground(new Color(0, 0, 0, 0));
        btnimprimir2.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PAINEL_GUIAS = new javax.swing.JTabbedPane();
        ALUNOS = new javax.swing.JPanel();
        tblalunos = new javax.swing.JScrollPane();
        tblclientes = new javax.swing.JTable();
        btnvoltar2 = new javax.swing.JButton();
        btnimprimir = new javax.swing.JButton();
        lblresul = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        cad_curso4 = new javax.swing.JLabel();
        CURSOS = new javax.swing.JPanel();
        tblcursos = new javax.swing.JScrollPane();
        tblclientes1 = new javax.swing.JTable();
        btnvoltar3 = new javax.swing.JButton();
        btnimprimir1 = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        lblresul1 = new javax.swing.JLabel();
        cad_curso3 = new javax.swing.JLabel();
        COORDENADORES = new javax.swing.JPanel();
        tblcoor = new javax.swing.JScrollPane();
        tblclientes2 = new javax.swing.JTable();
        btnvoltar4 = new javax.swing.JButton();
        btnimprimir2 = new javax.swing.JButton();
        lbl3 = new javax.swing.JLabel();
        lblresul2 = new javax.swing.JLabel();
        lblfundo3 = new javax.swing.JLabel();
        btntalunos = new javax.swing.JButton();
        btntcursos = new javax.swing.JButton();
        btntcoor = new javax.swing.JButton();
        btnvoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ALUNOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblclientes.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "RA", "Senha", "Nome", "Email", "Semestre", "Horas", "Curso"
            }
        ));
        tblclientes.setFocusable(false);
        tblclientes.setGridColor(new java.awt.Color(0, 0, 0));
        tblclientes.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblclientes.setRowHeight(30);
        tblclientes.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblclientes.getTableHeader().setReorderingAllowed(false);
        tblalunos.setViewportView(tblclientes);

        ALUNOS.add(tblalunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 870, 460));

        btnvoltar2.setBorder(null);
        btnvoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar2ActionPerformed(evt);
            }
        });
        ALUNOS.add(btnvoltar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 90, 40));

        btnimprimir.setBorder(null);
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });
        ALUNOS.add(btnimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 60, 50));

        lblresul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ALUNOS.add(lblresul, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 618, 100, 20));

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl1.setText("A média das horas cadastradas dos alunos é:");
        ALUNOS.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 310, -1));

        cad_curso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tabela_alunos1.png"))); // NOI18N
        ALUNOS.add(cad_curso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 740));

        PAINEL_GUIAS.addTab("tab2", ALUNOS);

        CURSOS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblclientes1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblclientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Semestres", "Total/Horas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblclientes1.setFocusable(false);
        tblclientes1.setGridColor(new java.awt.Color(0, 0, 0));
        tblclientes1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblclientes1.setRowHeight(30);
        tblclientes1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblclientes1.getTableHeader().setReorderingAllowed(false);
        tblcursos.setViewportView(tblclientes1);

        CURSOS.add(tblcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 860, 460));

        btnvoltar3.setBorder(null);
        btnvoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar3ActionPerformed(evt);
            }
        });
        CURSOS.add(btnvoltar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 90, 40));

        btnimprimir1.setBorder(null);
        btnimprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir1ActionPerformed(evt);
            }
        });
        CURSOS.add(btnimprimir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 60, 50));

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl2.setText("A média do total de semestres é:");
        CURSOS.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 230, -1));

        lblresul1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CURSOS.add(lblresul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 618, 100, 20));

        cad_curso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tabela_alunos1.png"))); // NOI18N
        CURSOS.add(cad_curso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 740));

        PAINEL_GUIAS.addTab("tab1", CURSOS);

        COORDENADORES.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblclientes2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblclientes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Login", "Senha", "Nome", "Turno", "Email", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblclientes2.setFocusable(false);
        tblclientes2.setGridColor(new java.awt.Color(0, 0, 0));
        tblclientes2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblclientes2.setRowHeight(30);
        tblclientes2.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblclientes2.getTableHeader().setReorderingAllowed(false);
        tblcoor.setViewportView(tblclientes2);

        COORDENADORES.add(tblcoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 880, 460));

        btnvoltar4.setBorder(null);
        btnvoltar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltar4ActionPerformed(evt);
            }
        });
        COORDENADORES.add(btnvoltar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 90, 40));

        btnimprimir2.setBorder(null);
        btnimprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir2ActionPerformed(evt);
            }
        });
        COORDENADORES.add(btnimprimir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 60, 50));

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl3.setText("coordenador(es) cadastrado(s)");
        COORDENADORES.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 620, 230, -1));

        lblresul2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        COORDENADORES.add(lblresul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 618, 50, 20));

        lblfundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tabela_coor1.png"))); // NOI18N
        lblfundo3.setPreferredSize(new java.awt.Dimension(1123, 758));
        COORDENADORES.add(lblfundo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        PAINEL_GUIAS.addTab("tab2", COORDENADORES);

        getContentPane().add(PAINEL_GUIAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, -33, 1120, -1));

        btntalunos.setBorder(null);
        btntalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntalunosActionPerformed(evt);
            }
        });
        getContentPane().add(btntalunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 210, 50));

        btntcursos.setBorder(null);
        btntcursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntcursosActionPerformed(evt);
            }
        });
        getContentPane().add(btntcursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 210, 50));

        btntcoor.setBorder(null);
        btntcoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntcoorActionPerformed(evt);
            }
        });
        getContentPane().add(btntcoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 210, 50));

        btnvoltar.setBorder(null);
        btnvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menu_tabs.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 290, 730));

        setSize(new java.awt.Dimension(1377, 730));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntalunosActionPerformed
        Tela_secretaria sec = new Tela_secretaria();
        sec.setVisible(true);
        dispose();
    }//GEN-LAST:event_btntalunosActionPerformed

    private void btntcursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntcursosActionPerformed
        try {
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select *from tab_coordenador";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tblclientes2.getModel();
            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("id"), rs.getString("login"), rs.getString("senha"), rs.getString("nome"), rs.getString("turno"), rs.getString("email"), rs.getString("curso_coor")});
            }

            rs.close();
            connection.close();

            int numrow = tblclientes2.getRowCount();

            lblresul2.setText(Integer.toString(numrow));

        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        PAINEL_GUIAS.setSelectedIndex(2);
    }//GEN-LAST:event_btntcursosActionPerformed

    private void btntcoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntcoorActionPerformed
        try {
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select *from tab_cursos";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tblclientes1.getModel();
            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("id"), rs.getString("nome"), rs.getString("total_semestres"), rs.getString("total_horas")});
            }

            rs.close();
            connection.close();

            int numrow = tblclientes1.getRowCount();
            float tot = 0;
            int cont = 0;

            for (int i = 0; i < numrow; i++) {
                float val = Float.valueOf(tblclientes1.getValueAt(i, 2).toString());
                cont++;
                tot = tot + val;
            }
            tot = tot / cont;
            DecimalFormat formatador = new DecimalFormat("0.00");
            formatador.format(tot);
            lblresul1.setText(Float.toString(tot).format("%.2f", tot));

        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        PAINEL_GUIAS.setSelectedIndex(1);
    }//GEN-LAST:event_btntcoorActionPerformed

    private void btnvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarActionPerformed
        try {
            Connection connection = new ConnectionFactory().getConnection();
            String sql = "select *from tab_alunos";
            PreparedStatement stmt = connection.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel modelo = (DefaultTableModel) tblclientes.getModel();
            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("id"), rs.getString("ra"), rs.getString("senha"), rs.getString("nome"), rs.getString("email"), rs.getString("semestre"), rs.getString("horas"), rs.getString("curso_aluno")});
            }

            rs.close();
            connection.close();

            int numrow = tblclientes.getRowCount();
            float tot = 0;
            int cont = 0;

            for (int i = 0; i < numrow; i++) {
                float val = Float.valueOf(tblclientes.getValueAt(i, 6).toString());
                cont++;
                tot = tot + val;
            }
            tot = tot / cont;
            DecimalFormat formatador = new DecimalFormat("0.00");
            formatador.format(tot);
            lblresul.setText(Float.toString(tot).format("%.2f", tot));

        } catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
        PAINEL_GUIAS.setSelectedIndex(0);
    }//GEN-LAST:event_btnvoltarActionPerformed

    private void btnvoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar2ActionPerformed
        PAINEL_GUIAS.setSelectedIndex(0);
    }//GEN-LAST:event_btnvoltar2ActionPerformed

    private void btnvoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar3ActionPerformed
        PAINEL_GUIAS.setSelectedIndex(0);    }//GEN-LAST:event_btnvoltar3ActionPerformed

    private void btnvoltar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltar4ActionPerformed
        PAINEL_GUIAS.setSelectedIndex(1);    }//GEN-LAST:event_btnvoltar4ActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        GeradorRelatorio relatorio = new GeradorRelatorio();
        relatorio.Gerar(this, "Tabela Alunos", "Alunos", tblclientes);    }//GEN-LAST:event_btnimprimirActionPerformed

    private void btnimprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir1ActionPerformed
        GeradorRelatorio relatorio = new GeradorRelatorio();
        relatorio.Gerar(this, "Tabela Cursos", "Cursos", tblclientes1);    }//GEN-LAST:event_btnimprimir1ActionPerformed

    private void btnimprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir2ActionPerformed
        GeradorRelatorio relatorio = new GeradorRelatorio();
        relatorio.Gerar(this, "Tabela Coordenadores", "Coordenadores", tblclientes2);    }//GEN-LAST:event_btnimprimir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            //FlatMaterialLighterContrastIJTheme.setup();
            //UIManager.put("TextComponent.arc", 10);
            //UIManager.put("Button.arc", 100);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_tabelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_tabelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_tabelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_tabelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_tabelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ALUNOS;
    private javax.swing.JPanel COORDENADORES;
    private javax.swing.JPanel CURSOS;
    private javax.swing.JTabbedPane PAINEL_GUIAS;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnimprimir1;
    private javax.swing.JButton btnimprimir2;
    private javax.swing.JButton btntalunos;
    private javax.swing.JButton btntcoor;
    private javax.swing.JButton btntcursos;
    private javax.swing.JButton btnvoltar;
    private javax.swing.JButton btnvoltar2;
    private javax.swing.JButton btnvoltar3;
    private javax.swing.JButton btnvoltar4;
    private javax.swing.JLabel cad_curso3;
    private javax.swing.JLabel cad_curso4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblfundo3;
    private javax.swing.JLabel lblresul;
    private javax.swing.JLabel lblresul1;
    private javax.swing.JLabel lblresul2;
    private javax.swing.JScrollPane tblalunos;
    private javax.swing.JTable tblclientes;
    private javax.swing.JTable tblclientes1;
    private javax.swing.JTable tblclientes2;
    private javax.swing.JScrollPane tblcoor;
    private javax.swing.JScrollPane tblcursos;
    // End of variables declaration//GEN-END:variables
}
